# Pranay Kumar
## Coding practical #1

In [8]:
import numpy as np

# ⬤ First Five Odd Integers

## List By Hand

In [9]:
OddList1 = [1,3,5,7,9] #Manually written list of first five odd integers.
print(OddList1)

[1, 3, 5, 7, 9]


## List By For Loop

In [10]:
Integers = np.arange(1,10,1) #Generated list of first ten integers.
OddList2 = [] #An empty list is created to store odd integers.
for x in Integers:
    if x%2==1:
        OddList2.append(x) #For each value in the list integers, we are dividing it by zero, and if the remainder is greater than one, then we add it to the odd list we created.
print(OddList2)

[1, 3, 5, 7, 9]


## List By List Comprehension

In [11]:
OddList3 = [x for x in range(10) if x%2==1] #Here we generate a list with the first five integers, but they are only added if the remainder is greater than zero, similar to the previous part.
print(OddList3)

[1, 3, 5, 7, 9]


## First Three Elements

In [12]:
OddList1[0:3] #We print the first three elements which start at the zero element and continue until the third element.

[1, 3, 5]

## Last Three Elements

In [13]:
OddList1[-3:] #We print a list of the last three elements by starting at element -3, which is just the 2nd element, and going forward.

[5, 7, 9]

# ⬤ 2-D List W/ Numbers and Integers

In [14]:
Letters = ["a","b","c"] #Letters a,b,c converted to a string.
IntegersNew = ["0","1","2"] #Numbers 0,1,2 converted to a string.
NewList = [] #Empty list to hold the 2-D list.
for x in IntegersNew:
    for y in Letters:
        NewList.append(x+y) #For all values in IntegersNew and then for all values in Letters, we add the elements and then append them into the new holding list.

NewList2 = np.reshape(NewList, (3,3)) #Converting the array into a 3x3 matrix to make it easier to interpret.
print("Numbers and Letters")
print(NewList2)
print("The order of the for loops matters because it determines what element comes first, here I chose numbers first, but if I had chosen letters, then the order would be different.")

Numbers and Letters
[['0a' '0b' '0c']
 ['1a' '1b' '1c']
 ['2a' '2b' '2c']]
The order of the for loops matters because it determines what element comes first, here I chose numbers first, but if I had chosen letters, then the order would be different.


# ⬤ Negative Multiples of Three

In [15]:
ArraySize = 14 #The integer we want to go up to.
MultipleVariable=3 #The variable we want to find multiples of.
Integers2 = np.array(range(ArraySize+1)) #Creating the array of up to the integer we designated earlier.
ThreeMultiples = [] #An empty list to hold future values.
for x in Integers2:
    if x%MultipleVariable==0:
        ThreeMultiples.append(x*-1) #For all elements in the array, we divide them by the variable we chose, and if the remainder is zero, then it is multiplied by negative one and added to the new list.
    else:
        ThreeMultiples.append(x) #Else if the remainder is not zero, then it is added to the list without being modified.
print(ThreeMultiples)

[0, 1, 2, -3, 4, 5, -6, 7, 8, -9, 10, 11, -12, 13, 14]


# ⬤ Integer Prime Function

In [16]:
def PrimeCheck(n):
    z = 0
    for x in range(2,n-1):
        if n%x != 0:
            pass
        else:
            z = 1
    if z==1:
        print(n, " is not a prime number.")
    else:
        print(n, " is a prime number")
PrimeCheck(20)

20  is not a prime number.


In [17]:
def fullPrimeFunctionCheck(n):
    PrimeList=[]
    NonPrimeList=[]
    z=0
    for x in range(1,n): #Goes through all integers from 1 to n.
        for y in range(2,x,1): #For the selected integer x, we then check for factors from 1 to x.
            if x%y != 0:
                pass #For all elements of y in the specified range, if the remainder of x divided y is not zero then the if statement passes.
            else:
                z=1 #Z gets set to one from zero if the value is divisible by element y in the specified range. This tells us that atleast one element from 2 to x-1 is a factor of x.
        if z==1:
            NonPrimeList.append(x) #If we know that x has some factor, then we can add it to the nonprime list.
        else:
            PrimeList.append(x) #Otherwise, n gets added to the prime list.
        z=0
    print("Prime numbers are    ",PrimeList)
    print("Nonprime numbers are ",NonPrimeList)
fullPrimeFunctionCheck(21)

Prime numbers are     [1, 2, 3, 5, 7, 11, 13, 17, 19]
Nonprime numbers are  [4, 6, 8, 9, 10, 12, 14, 15, 16, 18, 20]


# ⬤ Column Matrix

In [18]:
x1 = np.arange(1, 8, 1) #An array with integers from 1 to 7.
x2 = np.arange(1, 8, 1)**2 #This array is array x1 squared.
x3 = np.arange(1, 8, 1)**3 #This array is array x1 cubed.
data = np.vstack((x1,x2,x3)) #Converting the three arrays to a matrix.
transposed = np.transpose(data) #Transposing the matrix so that i, i^2, and i^3 are now columns with rows 1 to 7.
np.savetxt('ColumnMatrix.txt',transposed)

In [19]:
ColumnMatrixNew = np.loadtxt('ColumnMatrix.txt')
print(ColumnMatrixNew)

[[  1.   1.   1.]
 [  2.   4.   8.]
 [  3.   9.  27.]
 [  4.  16.  64.]
 [  5.  25. 125.]
 [  6.  36. 216.]
 [  7.  49. 343.]]
